# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c4118bb45a26a6b1b9133a2ad92a7b227ea5cf7499cc5116da60e8cfa4fc9782ec5ed11e37f8f5ebf41e889a57ae7c7b490eb9d4dc7e0d4edad165c9cb37ef0

test:
  secret_key_base: c5b071732003de6fb8f25413878e3c36bf72c256ef4ad3df1dfd0dba27890f612ccd0251b21e4ab5cee0cc9c0daa565111b99adf06a73c5520f3ceebc269b88e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
